#!/bin/bash
amazon-linux-extras install -y docker 
systemctl enable --now docker.service
curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
curl https://raw.githubusercontent.com/ruslangr/aws_wp/main/docker-compose-wp.yml > docker-compose.yml
docker-compose up -d
